version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    ports:
      - "3000:3000"
    volumes:
      - gitea_data:/data
    environment:
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__PROTOCOL=smtps
      - GITEA__mailer__SMTP_ADDR=smtp.gmail.com
      - GITEA__mailer__SMTP_PORT=465
      - GITEA__mailer__USER=sonakurian466@gmail.com
      - GITEA__mailer__PASSWD=<GMAIL_APP_PASSWORD>
      - GITEA__mailer__FROM=sonakurian466@gmail.com
      - GITEA__mailer__TLS=true

volumes:
  gitea_data:

